
server:
  port: 9091
---
spring:
  profiles: 
    active:
    - dev
 # sleuth:
 #   sampler:
 #     probability: 1.0
 # zipkin:
 #   base-url: http://localhost:9411/
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/toures_domain_usuario?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
    initialization-mode: always
    platform: mysql
  application:
    name: toures-balon-usuario
eureka:
  client:
  #  service-url: {"http://toures-balon-discovery:8761/eureka"}
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"
  instance:
    prefer-ip-address: true
userNotFoundMessage: "Usuario no Encontrado"
gema:
  kafka:
    producer:
      enabled: true
      bootstrap-server: htpp://192.168.0.6:29092